### ISSUE TITLE
Need a document.

### ISSUE THREAD

**Issue by QR-0W** [jexom/sd-webui-depth-lib#11]
So, I've got some pictures with hand to fix, and i wanna give it a try with this extension. But when I going to img2img, trying to fix hands with this extension by send the depth map it generated to the controlnet extension, the result was not satisfying. I can't figure out that whether i used this extension wrong, or something else.
So a document or some examples about how to use it would be 
I'm not that professional at this problem, and I'm not a native speaker, so maybe there's some problems with my text. 
But I'd pretty appreciate it if there is some examples available.

**Comment by jexom** [comment]
This extension does nothing to the generation in itself. That's what Control Net does. Using the depth maps comes down mostly to experimentation and all the extension provides is a set of depth maps so you don't have to go to blender or any other editor to make them.
I would suggest just asking people around on discord/reddit/wherever for advice and their experience of using the depth maps with control net because I myself couldn't really provide any as I didn't have the time to dive into it and mostly reroll until i get a good result.
